export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  dietary: ('vegetarian' | 'vegan' | 'gluten-free' | 'contains-nuts')[];
  tags: ('popular' | 'chef-recommendation' | 'new' | 'spicy')[];
  calories: number;
  image: string;
}

export const CATEGORIES = [
  'All',
  'Breakfast',
  'Shares',
  'Toasts & Sandwiches',
  'Pasta & Pizza',
  'Mains & Bowls',
  'Desserts',
  'Coffee & Drinks'
];

export const MENU_ITEMS: MenuItem[] = [
  // --- All Day Breakfast ---
  {
    id: 'turkish-eggs',
    name: 'Turkish Eggs',
    description: 'Poached eggs served over garlicky yogurt, topped with spicy paprika butter and fresh herbs.',
    price: 380,
    category: 'Breakfast',
    dietary: ['vegetarian'],
    tags: ['popular', 'chef-recommendation'],
    calories: 340,
    image: '/images/exp-food.png',
  },
  {
    id: 'french-omelette',
    name: 'French Omelette / Scramble',
    description: 'Served with hashbrowns & choice of bread (Sourdough or Hokkaido). Option to add cheese, indie masala, truffle mushroom, or chicken.',
    price: 300,
    category: 'Breakfast',
    dietary: [],
    tags: [],
    calories: 420,
    image: '/images/exp-food.png',
  },
  {
    id: 'akuri-tofu',
    name: 'Akuri Tofu',
    description: 'Soft tofu cooked with onions, tomatoes, chilies, and warm spices, served with sourdough toast.',
    price: 400,
    category: 'Breakfast',
    dietary: ['vegetarian', 'vegan'],
    tags: ['new'],
    calories: 280,
    image: '/images/exp-food.png',
  },
  {
    id: 'buttermilk-pancakes',
    name: 'Buttermilk Pancakes',
    description: 'Soft and fluffy pancakes, served with maple syrup and a pat of butter. Optionally add chocolate or berry toppings.',
    price: 400,
    category: 'Breakfast',
    dietary: ['vegetarian'],
    tags: ['popular'],
    calories: 480,
    image: '/images/exp-food.png',
  },

  // --- Soups & Salads & Shares (Shares category) ---
  {
    id: 'wild-mushroom-soup',
    name: 'Wild Mushroom Soup',
    description: 'Creamy wild mushroom soup, rich in earthy flavors and finished with a drizzle of truffle oil.',
    price: 350,
    category: 'Shares',
    dietary: ['vegetarian'],
    tags: ['popular'],
    calories: 190,
    image: '/images/exp-food.png',
  },
  {
    id: 'cream-of-tomato',
    name: 'Cream of Tomato Soup',
    description: 'A rich and velvety blend of ripe tomatoes, fresh cream, and aromatic herbs.',
    price: 310,
    category: 'Shares',
    dietary: ['vegetarian'],
    tags: [],
    calories: 150,
    image: '/images/exp-food.png',
  },
  {
    id: 'caesar-salad',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce tossed with creamy Caesar dressing, parmesan, and crunchy croutons.',
    price: 480,
    category: 'Shares',
    dietary: ['vegetarian'],
    tags: [],
    calories: 290,
    image: '/images/exp-food.png',
  },
  {
    id: 'french-country-salad',
    name: 'French Country Salad',
    description: 'A rustic mix of fresh greens, roasted beets, cherry tomatoes, walnuts, and feta cheese, tossed in a classic passionfruit vinaigrette.',
    price: 490,
    category: 'Shares',
    dietary: ['vegetarian', 'contains-nuts'],
    tags: ['chef-recommendation'],
    calories: 320,
    image: '/images/exp-food.png',
  },
  {
    id: 'loaded-nachos',
    name: 'Loaded Nachos',
    description: 'Crispy tortilla chips loaded with melted cheese, jalapeños, beans, salsa, sour cream, and guacamole.',
    price: 430,
    category: 'Shares',
    dietary: ['vegetarian'],
    tags: ['popular'],
    calories: 550,
    image: '/images/exp-food.png',
  },
  {
    id: 'jalapeno-poppers',
    name: 'Jalapeño Cheese Poppers',
    description: 'Crispy-fried jalapeños stuffed with creamy cheese, served with a tangy dipping sauce.',
    price: 470,
    category: 'Shares',
    dietary: ['vegetarian'],
    tags: ['spicy'],
    calories: 380,
    image: '/images/exp-food.png',
  },
  {
    id: 'avocado-sevpuri',
    name: 'Avocado Sevpuri',
    description: 'Crisp puris topped with creamy avocado, tangy chutneys, crunchy sev, and a burst of fresh herbs.',
    price: 480,
    category: 'Shares',
    dietary: ['vegetarian'],
    tags: ['popular', 'new'],
    calories: 310,
    image: '/images/exp-food.png',
  },
  {
    id: 'steamed-edamame',
    name: 'Steamed Edamame',
    description: 'Young soybeans lightly steamed and sprinkled with sea salt.',
    price: 550,
    category: 'Shares',
    dietary: ['vegetarian', 'vegan', 'gluten-free'],
    tags: [],
    calories: 120,
    image: '/images/exp-food.png',
  },
  {
    id: 'hummus-pita',
    name: 'Hummus & Pita',
    description: 'Creamy hummus served with warm pita bread and crispy lavash.',
    price: 450,
    category: 'Shares',
    dietary: ['vegetarian', 'vegan'],
    tags: [],
    calories: 340,
    image: '/images/exp-food.png',
  },
  {
    id: 'garlic-bread',
    name: 'Pull Apart Garlic Bread',
    description: 'Soft, buttery bread infused with garlic, herbs, and melted cheese.',
    price: 435,
    category: 'Shares',
    dietary: ['vegetarian'],
    tags: ['popular'],
    calories: 410,
    image: '/images/exp-food.png',
  },
  {
    id: 'cheese-corndog',
    name: 'Cheese Corndog',
    description: 'Melty mozzarella coated in a crispy, golden batter, drizzled with mustard and ketchup.',
    price: 490,
    category: 'Shares',
    dietary: ['vegetarian'],
    tags: ['new'],
    calories: 450,
    image: '/images/exp-food.png',
  },
  {
    id: 'chicken-wings',
    name: 'Chicken Wings',
    description: 'Fiery chicken wings tossed in a scorching, authentic bhoot jolokia sauce.',
    price: 485,
    category: 'Shares',
    dietary: [],
    tags: ['spicy'],
    calories: 520,
    image: '/images/exp-food.png',
  },
  {
    id: 'podi-popcorn',
    name: 'Podi Chicken Popcorn',
    description: 'Crispy bite-sized chicken coated in South Indian-style spicy podi masala.',
    price: 470,
    category: 'Shares',
    dietary: [],
    tags: ['spicy', 'chef-recommendation'],
    calories: 460,
    image: '/images/exp-food.png',
  },
  {
    id: 'fish-chips',
    name: 'Fish & Chips',
    description: 'Crispy golden fried fish served with fries, house tartar sauce, and a wedge of lemon.',
    price: 610,
    category: 'Shares',
    dietary: [],
    tags: ['popular'],
    calories: 640,
    image: '/images/exp-food.png',
  },

  // --- Dim Sums (Shares Category) ---
  {
    id: 'truffle-edamame-dimsum',
    name: 'Truffle Edamame Dim Sums',
    description: 'Edamame-stuffed dim sums (5 pieces) infused with aromatic truffle oil, served with soy-chili dip.',
    price: 610,
    category: 'Shares',
    dietary: ['vegetarian'],
    tags: ['chef-recommendation'],
    calories: 210,
    image: '/images/exp-food.png',
  },
  {
    id: 'burnt-garlic-dimsum',
    name: 'Burnt Garlic Dim Sums',
    description: 'Dim sums (5 pieces) stuffed with spiced seasonal vegetables and tossed in smoky burnt garlic oil.',
    price: 560,
    category: 'Shares',
    dietary: ['vegetarian'],
    tags: [],
    calories: 180,
    image: '/images/exp-food.png',
  },
  {
    id: 'charcoal-chicken-dimsum',
    name: 'Charcoal Chicken Dim Sums',
    description: 'Smoky charcoal-chicken stuffed dim sums (5 pieces) with bold spices, served with a hot garlic dip.',
    price: 600,
    category: 'Shares',
    dietary: [],
    tags: ['popular', 'new'],
    calories: 240,
    image: '/images/exp-food.png',
  },

  // --- Toasts & Sandwiches ---
  {
    id: 'avocado-toast',
    name: 'Avocado Toast',
    description: 'Toasted sourdough topped with seasoned sliced avocado, chili flakes, and a fresh squeeze of lemon.',
    price: 530,
    category: 'Toasts & Sandwiches',
    dietary: ['vegetarian', 'vegan'],
    tags: ['popular'],
    calories: 320,
    image: '/images/exp-food.png',
  },
  {
    id: 'guacamole-toast',
    name: 'Guacamole Toast',
    description: 'Crunchy artisan toast layered with zesty guacamole, cherry tomatoes, and a sprinkle of microgreens.',
    price: 540,
    category: 'Toasts & Sandwiches',
    dietary: ['vegetarian', 'vegan'],
    tags: [],
    calories: 340,
    image: '/images/exp-food.png',
  },
  {
    id: 'shroom-on-toast',
    name: 'Shroom on Toast',
    description: 'Sautéed wild mushrooms in garlic butter, served on toasted sourdough with a hint of fresh thyme.',
    price: 420,
    category: 'Toasts & Sandwiches',
    dietary: ['vegetarian'],
    tags: [],
    calories: 290,
    image: '/images/exp-food.png',
  },
  {
    id: 'caprese-toast',
    name: 'Caprese Toast',
    description: 'Toasted sourdough topped with fresh mozzarella, tomatoes, basil, and a drizzle of balsamic glaze.',
    price: 460,
    category: 'Toasts & Sandwiches',
    dietary: ['vegetarian'],
    tags: ['new'],
    calories: 380,
    image: '/images/exp-food.png',
  },
  {
    id: 'crispy-chicken-swich',
    name: "Crispy Chicken S'wich",
    description: 'Crispy fried chicken, lettuce, pickles, and creamy house mayo pressed in warm brioche bread.',
    price: 480,
    category: 'Toasts & Sandwiches',
    dietary: [],
    tags: ['popular'],
    calories: 590,
    image: '/images/exp-food.png',
  },
  {
    id: 'grilled-cheese-swich',
    name: "Grilled Cheese S'wich",
    description: 'Golden toasted brioche bread layered with melted cheddar and mozzarella. Served with a side of hot tomato soup.',
    price: 440,
    category: 'Toasts & Sandwiches',
    dietary: ['vegetarian'],
    tags: ['chef-recommendation'],
    calories: 680,
    image: '/images/exp-food.png',
  },

  // --- Pasta, Pizza & Ramen (Pasta & Pizza Category) ---
  {
    id: 'truffle-mushroom-fettuccine',
    name: 'Truffle Mushroom Fettuccine',
    description: 'Silky fettuccine tossed in a creamy white truffle sauce, wild forest mushrooms, and shaved parmesan.',
    price: 565,
    category: 'Pasta & Pizza',
    dietary: ['vegetarian'],
    tags: ['popular', 'chef-recommendation'],
    calories: 680,
    image: '/images/exp-food.png',
  },
  {
    id: 'pomodoro-rigatoni',
    name: 'Pomodoro Rigatoni',
    description: 'Rigatoni pasta tossed in slow-cooked tomato pomodoro sauce, fresh basil, and grated parmesan.',
    price: 560,
    category: 'Pasta & Pizza',
    dietary: ['vegetarian'],
    tags: [],
    calories: 450,
    image: '/images/exp-food.png',
  },
  {
    id: 'bolognese-fettuccine',
    name: 'Bolognese Fettuccine',
    description: 'Silky fettuccine topped with a hearty, slow-simmered minced meat Bolognese sauce and parmesan.',
    price: 620,
    category: 'Pasta & Pizza',
    dietary: [],
    tags: ['popular'],
    calories: 710,
    image: '/images/exp-food.png',
  },
  {
    id: 'margherita-pizza',
    name: 'Margherita Pizza',
    description: 'Wood-fired crust topped with San Marzano tomato sauce, fresh Mozzarella blend, and aromatic sweet basil.',
    price: 570,
    category: 'Pasta & Pizza',
    dietary: ['vegetarian'],
    tags: ['popular'],
    calories: 820,
    image: '/images/exp-food.png',
  },
  {
    id: 'truffle-funghi-pizza',
    name: 'Truffle Funghi Pizza',
    description: 'Wood-fired crust with San Marzano tomato sauce, Mozzarella blend, wild mushrooms, and a drizzle of truffle oil.',
    price: 620,
    category: 'Pasta & Pizza',
    dietary: ['vegetarian'],
    tags: ['chef-recommendation'],
    calories: 890,
    image: '/images/exp-food.png',
  },
  {
    id: 'og-shin-slurp',
    name: 'OG Shin Slurp Ramen',
    description: 'Iconic Shin Ramyun served in a peppery hot broth with chewy noodles. Custom add-ons available.',
    price: 300,
    category: 'Pasta & Pizza',
    dietary: [],
    tags: [],
    calories: 510,
    image: '/images/exp-food.png',
  },
  {
    id: 'spicy-carbonara-ramen',
    name: 'Spicy Carbonara Ramen',
    description: 'Spicy Korean fire noodles tossed in a creamy carbonara sauce, topped with melted cheese slices.',
    price: 350,
    category: 'Pasta & Pizza',
    dietary: [],
    tags: ['spicy', 'popular'],
    calories: 640,
    image: '/images/exp-food.png',
  },

  // --- Mains & Bowls ---
  {
    id: 'green-goddess-bowl',
    name: 'Green Goddess Bowl',
    description: 'A nutrient-dense bowl with avocado, nuts, quinoa, fresh Malta orange, crunchy lettuce, and a zesty malta orange dressing.',
    price: 640,
    category: 'Mains & Bowls',
    dietary: ['vegetarian', 'vegan', 'contains-nuts'],
    tags: ['new', 'chef-recommendation'],
    calories: 450,
    image: '/images/exp-food.png',
  },
  {
    id: 'grilled-chicken-main',
    name: 'Grilled Chicken Platter',
    description: 'Juicy grilled chicken breast served with creamy mashed potatoes, sautéed market vegetables, and rich mushroom pepper sauce.',
    price: 620,
    category: 'Mains & Bowls',
    dietary: [],
    tags: ['popular'],
    calories: 580,
    image: '/images/exp-food.png',
  },
  {
    id: 'grilled-paneer-main',
    name: 'Grilled Paneer Platter',
    description: 'Spiced grilled paneer steak served with mashed potatoes, sautéed vegetables, and a tangy paprika cream sauce.',
    price: 600,
    category: 'Mains & Bowls',
    dietary: ['vegetarian'],
    tags: [],
    calories: 540,
    image: '/images/exp-food.png',
  },
  {
    id: 'thai-curry-bowl',
    name: 'Thai Curry Bowl',
    description: 'Fragrant and aromatic green Thai curry simmered in coconut milk and fresh herbs, served with steamed jasmine rice.',
    price: 610,
    category: 'Mains & Bowls',
    dietary: ['vegetarian'],
    tags: [],
    calories: 490,
    image: '/images/exp-food.png',
  },
  {
    id: 'ghee-roast',
    name: 'Mangalorean Ghee Roast',
    description: 'Rich, spicy, and tangy ghee roast (choice of mushroom or chicken) served with two flaky Malabar Parottas.',
    price: 680,
    category: 'Mains & Bowls',
    dietary: [],
    tags: ['spicy', 'chef-recommendation'],
    calories: 720,
    image: '/images/exp-food.png',
  },

  // --- Desserts ---
  {
    id: 'chocolate-brownie',
    name: 'Gooey Chocolate Brownie',
    description: 'Warm, dense chocolate fudge brownie served with a scoop of premium vanilla bean ice cream.',
    price: 470,
    category: 'Desserts',
    dietary: ['vegetarian'],
    tags: ['popular'],
    calories: 410,
    image: '/images/exp-food.png',
  },
  {
    id: 'tiramisu',
    name: 'Signature Tiramisu',
    description: 'Espresso-soaked ladyfinger biscuits layered with a rich whipped mascarpone cream and finished with cocoa powder.',
    price: 470,
    category: 'Desserts',
    dietary: ['vegetarian'],
    tags: ['chef-recommendation', 'popular'],
    calories: 380,
    image: '/images/exp-food.png',
  },
  {
    id: 'skillet-cookie',
    name: 'Skillet Chocolate Chip Cookie',
    description: 'Warm, gooey chocolate chip cookie baked fresh in a cast-iron skillet, topped with vanilla ice cream and warm chocolate sauce.',
    price: 350,
    category: 'Desserts',
    dietary: ['vegetarian'],
    tags: ['new'],
    calories: 580,
    image: '/images/exp-food.png',
  },

  // --- Coffee & Drinks ---
  {
    id: 'espresso',
    name: 'Espresso',
    description: 'A concentrated shot of our signature roasted espresso beans. Bold and intense.',
    price: 190,
    category: 'Coffee & Drinks',
    dietary: ['vegetarian', 'vegan', 'gluten-free'],
    tags: [],
    calories: 5,
    image: '/images/exp-coffee.png',
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    description: 'Equal parts espresso, steamed milk, and rich microfoam. Classic balance.',
    price: 260,
    category: 'Coffee & Drinks',
    dietary: ['vegetarian'],
    tags: ['popular'],
    calories: 120,
    image: '/images/exp-coffee.png',
  },
  {
    id: 'latte',
    name: 'Latte',
    description: 'Espresso shot with steamed milk and a thin layer of milk foam on top.',
    price: 280,
    category: 'Coffee & Drinks',
    dietary: ['vegetarian'],
    tags: [],
    calories: 150,
    image: '/images/exp-coffee.png',
  },
  {
    id: 'spanish-latte-hot',
    name: 'Spanish Latte (House Special)',
    description: 'Our signature double espresso sweetened with condensed milk and combined with steamed milk.',
    price: 300,
    category: 'Coffee & Drinks',
    dietary: ['vegetarian'],
    tags: ['popular', 'chef-recommendation'],
    calories: 220,
    image: '/images/exp-coffee.png',
  },
  {
    id: 'cold-coffee',
    name: 'Signature Cold Coffee',
    description: 'Classic creamy blended cold coffee, perfectly sweetened and served chilled.',
    price: 370,
    category: 'Coffee & Drinks',
    dietary: ['vegetarian'],
    tags: ['popular'],
    calories: 260,
    image: '/images/exp-coffee.png',
  },
  {
    id: 'vietnamese-iced',
    name: 'Vietnamese Iced Coffee',
    description: 'Traditional slow-dripped intense coffee poured over ice and sweet condensed milk.',
    price: 370,
    category: 'Coffee & Drinks',
    dietary: ['vegetarian'],
    tags: ['new'],
    calories: 210,
    image: '/images/exp-coffee.png',
  },
  {
    id: 'biscoff-shake',
    name: 'Biscoff Milkshake',
    description: 'Thick, creamy milkshake blended with original Lotus Biscoff cookies and spread.',
    price: 400,
    category: 'Coffee & Drinks',
    dietary: ['vegetarian'],
    tags: ['popular'],
    calories: 490,
    image: '/images/exp-coffee.png',
  },
  {
    id: 'orange-spritz',
    name: 'Orange Spritz Mocktail',
    description: 'Sparkling and refreshing spritz infused with fresh orange zest and key lime tonic.',
    price: 390,
    category: 'Coffee & Drinks',
    dietary: ['vegetarian', 'vegan', 'gluten-free'],
    tags: ['new'],
    calories: 90,
    image: '/images/exp-coffee.png',
  },
  {
    id: 'chamomile-tea',
    name: 'Egyptian Chamomile Tea',
    description: 'A soothing caffeine-free herbal infusion made from whole chamomile flowers.',
    price: 290,
    category: 'Coffee & Drinks',
    dietary: ['vegetarian', 'vegan', 'gluten-free'],
    tags: [],
    calories: 2,
    image: '/images/exp-coffee.png',
  }
];
